[project]
name = "tl-shortcut-img2markdown"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.69.0",
    "pillow>=11.1.0",
    "pyperclip>=1.9.0",
    "pyqt5>=5.15.11",
    "python-dotenv>=1.1.0",
]
